"""
core/reporter.py — HTML report generator for SPECTRE.
Reads all .log files from logs/ and produces a single HTML report.
"""

import os
import re
from datetime import datetime


REPORT_DIR = "reports"


def generate_report() -> str:
    """Build HTML report from all logs. Returns the output file path."""
    os.makedirs(REPORT_DIR, exist_ok=True)

    logs_dir = "logs"
    log_files = sorted(
        [f for f in os.listdir(logs_dir) if f.endswith(".log")],
        reverse=True
    ) if os.path.exists(logs_dir) else []

    sections = []
    for fname in log_files:
        fpath = os.path.join(logs_dir, fname)
        with open(fpath, encoding="utf-8") as f:
            content = f.read()
        sections.append(_make_section(fname, content))

    ts        = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ts_file   = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    out_path  = os.path.join(REPORT_DIR, f"spectre_report_{ts_file}.html")

    html = _build_html(ts, sections)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)

    return out_path


def _make_section(fname: str, content: str) -> str:
    title = fname.replace("_", " ").replace(".log", "").title()
    escaped = content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return f"""
    <div class="section">
        <h2>{title}</h2>
        <pre>{escaped}</pre>
    </div>"""


def _build_html(timestamp: str, sections: list) -> str:
    body = "\n".join(sections) if sections else "<p>No scan logs found.</p>"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SPECTRE 2.0 — Report</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #0d0d0d; color: #c8fffc;
    font-family: 'Courier New', monospace; padding: 2rem;
  }}
  header {{
    border-bottom: 1px solid #00e5ff; padding-bottom: 1rem; margin-bottom: 2rem;
  }}
  h1 {{ color: #00e5ff; font-size: 2rem; letter-spacing: 4px; }}
  .meta {{ color: #555; margin-top: 0.5rem; font-size: 0.85rem; }}
  .section {{
    background: #111; border: 1px solid #1a1a1a;
    border-left: 3px solid #00e5ff;
    margin-bottom: 1.5rem; padding: 1.2rem;
    border-radius: 4px;
  }}
  h2 {{ color: #00e5ff; font-size: 1rem; margin-bottom: 1rem;
        text-transform: uppercase; letter-spacing: 2px; }}
  pre {{
    white-space: pre-wrap; word-break: break-all;
    font-size: 0.82rem; line-height: 1.6; color: #a0f0ed;
  }}
  footer {{ margin-top: 2rem; color: #333; font-size: 0.75rem; }}
</style>
</head>
<body>
<header>
  <h1>&#9650; SPECTRE 2.0</h1>
  <p class="meta">Portable Network Inspection &amp; Security Toolkit</p>
  <p class="meta">Report generated: {timestamp}</p>
</header>

{body}

<footer>Generated by SPECTRE 2.0 &mdash; For authorized use only.</footer>
</body>
</html>"""
